"""Script to assemble, leakage-check, and persist Phase 4 synthetic query pairs.

Ensures:
1. Exact schema compliance with query_pair_reuse_benchmark.json.
2. 100% zero leakage against all 5 existing datasets:
   - data/raw/query_pair_reuse_benchmark.json
   - data/raw/query_stability_benchmark.json
   - data/raw/query_stability_benchmark_heldout.json
   - data/raw/query_stability_benchmark_final_test.json
   - data/raw/query_stability_human_credibility.json
3. Internal uniqueness across all authored queries.
4. Balanced safe/unsafe representation across starved categories.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Any, Dict, List, Set

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = REPO_ROOT / "data" / "raw"
OUTPUT_PATH = DATA_DIR / "synthetic_query_pair_feedback.json"

EXISTING_DATASET_PATHS = {
    "pair_benchmark": DATA_DIR / "query_pair_reuse_benchmark.json",
    "stability_dev": DATA_DIR / "query_stability_benchmark.json",
    "stability_heldout": DATA_DIR / "query_stability_benchmark_heldout.json",
    "stability_final_test": DATA_DIR / "query_stability_benchmark_final_test.json",
    "stability_human_cred": DATA_DIR / "query_stability_human_credibility.json",
}

SYNTHETIC_PAIRS: List[Dict[str, Any]] = [
    # -----------------------------------------------------------------------
    # MATHEMATICS (18 pairs: 8 safe, 10 unsafe)
    # -----------------------------------------------------------------------
    {
        "id": "SYNTH-001",
        "query_a": "How do you calculate the determinant of a 2x2 matrix?",
        "query_b": "Formula for finding the determinant of a 2 by 2 matrix",
        "domain": "mathematics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both queries request the exact formula (ad - bc) for the determinant of a 2x2 matrix.",
    },
    {
        "id": "SYNTH-002",
        "query_a": "What is the quadratic formula used to solve ax^2 + bx + c = 0?",
        "query_b": "State the quadratic equation solution formula for finding roots",
        "domain": "mathematics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both seek the standard algebraic quadratic formula (-b +/- sqrt(b^2 - 4ac)) / (2a).",
    },
    {
        "id": "SYNTH-003",
        "query_a": "How do you find the derivative of sin(x) with respect to x?",
        "query_b": "What is d/dx of sin(x) in calculus?",
        "domain": "mathematics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Exact same calculus operation requesting the derivative of sin(x), which is cos(x).",
    },
    {
        "id": "SYNTH-004",
        "query_a": "What is the Pythagorean theorem relating right triangle sides?",
        "query_b": "State the Pythagorean theorem formula a^2 + b^2 = c^2",
        "domain": "mathematics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both queries request the fundamental geometric relation between the sides of a right triangle.",
    },
    {
        "id": "SYNTH-005",
        "query_a": "How do you compute the arithmetic mean of a dataset?",
        "query_b": "What is the formula to calculate the average of a set of numbers?",
        "domain": "mathematics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Arithmetic mean and average of numbers are exact mathematical synonyms.",
    },
    {
        "id": "SYNTH-006",
        "query_a": "What is the factorial of zero defined as?",
        "query_b": "What is the value of 0! in mathematics?",
        "domain": "mathematics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both ask for the exact value and definition of 0 factorial (which is 1).",
    },
    {
        "id": "SYNTH-007",
        "query_a": "How do you calculate the perimeter of a rectangle with length l and width w?",
        "query_b": "Formula for finding the perimeter of a rectangle",
        "domain": "mathematics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both request the geometric perimeter formula 2*(l + w) for a rectangle.",
    },
    {
        "id": "SYNTH-008",
        "query_a": "What is the sum of interior angles in a triangle in Euclidean geometry?",
        "query_b": "How many degrees do the interior angles of a planar triangle add up to?",
        "domain": "mathematics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both ask for the constant sum of interior angles in a planar triangle (180 degrees).",
    },
    {
        "id": "SYNTH-009",
        "query_a": "How do you calculate the permutation P(n, k)?",
        "query_b": "How do you calculate the combination C(n, k)?",
        "domain": "mathematics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Combinatorial mismatch: permutations account for sequence order (n!/(n-k)!), whereas combinations do not (n!/(k!(n-k)!)).",
        "rationale": "High lexical overlap but fundamentally distinct combinatorial formulas.",
    },
    {
        "id": "SYNTH-010",
        "query_a": "What is the derivative of e^x with respect to x?",
        "query_b": "What is the integral of e^x with respect to x with constant of integration?",
        "domain": "mathematics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Calculus operation mismatch: derivative evaluation (e^x) omits the integration constant required for indefinite integral (e^x + C).",
        "rationale": "Different fundamental operations: differentiation vs integration.",
    },
    {
        "id": "SYNTH-011",
        "query_a": "How do you find the eigenvalues of a square matrix?",
        "query_b": "How do you find the eigenvectors corresponding to a known eigenvalue?",
        "domain": "mathematics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Mathematical object mismatch: finding scalar characteristic polynomial roots vs solving (A - lambda*I)v = 0 for vector basis.",
        "rationale": "Shared linear algebra topic, but scalar root computation does not solve the null space vector.",
    },
    {
        "id": "SYNTH-012",
        "query_a": "What is the formula for the surface area of a cylinder?",
        "query_b": "What is the formula for the volume of a cylinder?",
        "domain": "mathematics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Dimensionality mismatch: 2D total surface area (2*pi*r*h + 2*pi*r^2) vs 3D volume capacity (pi*r^2*h).",
        "rationale": "Surface area vs volume for the same geometric solid.",
    },
    {
        "id": "SYNTH-013",
        "query_a": "How do you solve a system of linear equations using Gaussian elimination?",
        "query_b": "How do you solve a system of non-linear equations using Newton-Raphson?",
        "domain": "mathematics",
        "semantic_similarity_level": "MEDIUM",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Linear algebraic row-reduction algorithm does not apply to non-linear multivariable Jacobian iteration.",
        "rationale": "Linear exact solver vs non-linear iterative numerical solver.",
    },
    {
        "id": "SYNTH-014",
        "query_a": "What is the formula for population standard deviation?",
        "query_b": "What is the formula for sample standard deviation with Bessel's correction?",
        "domain": "mathematics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_CONTEXT_MISMATCH",
        "rejection_reason": "Statistical denominator mismatch: population uses N, sample standard deviation requires degrees of freedom N-1.",
        "rationale": "Subtle mathematical constraint difference that produces biased estimates if swapped.",
    },
    {
        "id": "SYNTH-015",
        "query_a": "How do you compute the dot product of two vectors?",
        "query_b": "How do you compute the cross product of two 3D vectors?",
        "domain": "mathematics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Output type mismatch: dot product produces a scalar, while cross product produces an orthogonal 3D vector.",
        "rationale": "Vector algebra operations with different algebraic structures and outputs.",
    },
    {
        "id": "SYNTH-016",
        "query_a": "What is the definition of a rational number?",
        "query_b": "What is the definition of an irrational number?",
        "domain": "mathematics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Polarity definition mismatch: expressible as a ratio of integers a/b vs cannot be written as a simple fraction.",
        "rationale": "Complementary number subsets with opposing mathematical definitions.",
    },
    {
        "id": "SYNTH-017",
        "query_a": "What is the sum of an infinite convergent geometric series with |r| < 1?",
        "query_b": "What is the formula for the sum of the first n terms of a finite geometric series?",
        "domain": "mathematics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_CONTEXT_MISMATCH",
        "rejection_reason": "Convergence limit mismatch: infinite limit a/(1-r) does not solve the finite n-term partial sum a*(1-r^n)/(1-r).",
        "rationale": "Infinite limit vs finite n-term truncation.",
    },
    {
        "id": "SYNTH-018",
        "query_a": "How do you convert radians to degrees?",
        "query_b": "How do you convert degrees to radians?",
        "domain": "mathematics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Conversion factor inversion: multiplying by 180/pi vs multiplying by pi/180.",
        "rationale": "Reciprocal conversion factors; serving cached answer yields an inverted result.",
    },

    # -----------------------------------------------------------------------
    # SYSTEM OPERATIONS (18 pairs: 10 safe, 8 unsafe)
    # -----------------------------------------------------------------------
    {
        "id": "SYNTH-019",
        "query_a": "How do I check free disk space on Linux using terminal?",
        "query_b": "Command to view available disk space in Linux CLI",
        "domain": "system_operations",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both queries ask for the standard Linux df -h command to inspect disk usage.",
    },
    {
        "id": "SYNTH-020",
        "query_a": "How do I show current running processes in Linux?",
        "query_b": "Command to list active processes in a Linux terminal",
        "domain": "system_operations",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both request process listing commands (ps aux or top) in Linux.",
    },
    {
        "id": "SYNTH-021",
        "query_a": "How do I create a new directory in bash terminal?",
        "query_b": "Linux command to make a new folder from command line",
        "domain": "system_operations",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Directory and folder are exact synonyms; both seek the mkdir command.",
    },
    {
        "id": "SYNTH-022",
        "query_a": "How do I check my local IP address on Ubuntu Linux?",
        "query_b": "Linux command to display local network IP address",
        "domain": "system_operations",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both ask for network interface IP discovery (ip addr show / hostname -I).",
    },
    {
        "id": "SYNTH-023",
        "query_a": "How do I restart the systemd service named nginx on Ubuntu?",
        "query_b": "Command to restart nginx service using systemctl in Linux",
        "domain": "system_operations",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both request the exact command: sudo systemctl restart nginx.",
    },
    {
        "id": "SYNTH-024",
        "query_a": "How do I view the last 100 lines of a log file in Linux?",
        "query_b": "Linux command to print the trailing 100 lines of a log file",
        "domain": "system_operations",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both request the tail -n 100 <file> command.",
    },
    {
        "id": "SYNTH-025",
        "query_a": "How do I unpack a tar.gz compressed archive in Linux?",
        "query_b": "Command to extract tar.gz file on Linux command line",
        "domain": "system_operations",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Unpack and extract are exact synonyms for tar -xzvf archive.tar.gz.",
    },
    {
        "id": "SYNTH-026",
        "query_a": "How do I test network connectivity to a remote host using ping?",
        "query_b": "Command to ping a remote server to check if it is reachable",
        "domain": "system_operations",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both describe testing host reachability via ICMP ping.",
    },
    {
        "id": "SYNTH-027",
        "query_a": "How do I print the current working directory in bash?",
        "query_b": "Linux command to show present working directory path",
        "domain": "system_operations",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both seek the pwd command in Unix/Linux shell.",
    },
    {
        "id": "SYNTH-028",
        "query_a": "How do I count the number of lines in a text file using wc on Linux?",
        "query_b": "Linux command to get total line count of a file with wc",
        "domain": "system_operations",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both ask for wc -l <filename> in Linux.",
    },
    {
        "id": "SYNTH-029",
        "query_a": "How do I recursively change file permissions to 755 in Linux?",
        "query_b": "How do I recursively change file permissions to 644 in Linux?",
        "domain": "system_operations",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_CONTEXT_MISMATCH",
        "rejection_reason": "Permission mode conflict: 755 grants execution bits (rwxr-xr-x), while 644 is non-executable (rw-r--r--).",
        "rationale": "High textual similarity with opposing security permission bitmasks.",
    },
    {
        "id": "SYNTH-030",
        "query_a": "How do I stop a running Docker container gracefully?",
        "query_b": "How do I force kill and remove a running Docker container?",
        "domain": "system_operations",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Destructive operation discrepancy: SIGTERM graceful stop vs SIGKILL and container deletion (docker rm -f).",
        "rationale": "Graceful pause vs destructive immediate purge.",
    },
    {
        "id": "SYNTH-031",
        "query_a": "How do I find files modified in the last 24 hours on Linux?",
        "query_b": "How do I find and delete files modified more than 30 days ago on Linux?",
        "domain": "system_operations",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Destructive action & timeframe mismatch: read-only recent query (mtime -1) vs destructive file deletion on aged files (-mtime +30 -delete).",
        "rationale": "Read-only recent query vs destructive purge.",
    },
    {
        "id": "SYNTH-032",
        "query_a": "How do I append text to an existing file in bash?",
        "query_b": "How do I overwrite an existing file with new text in bash?",
        "domain": "system_operations",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_CONTEXT_MISMATCH",
        "rejection_reason": "File I/O mode mismatch: append (>>) preserves existing contents, overwrite (>) truncates and destroys previous data.",
        "rationale": "Destructive truncation vs non-destructive concatenation.",
    },
    {
        "id": "SYNTH-033",
        "query_a": "How do I change the owner of a file in Linux using chown?",
        "query_b": "How do I change the group ownership of a file in Linux using chgrp?",
        "domain": "system_operations",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Principal mismatch: changing user ID (UID) ownership vs changing group ID (GID) assignment.",
        "rationale": "Different POSIX ownership attributes.",
    },
    {
        "id": "SYNTH-034",
        "query_a": "How do I inspect HTTP response headers using curl on Linux?",
        "query_b": "How do I download a file directly to disk using curl on Linux?",
        "domain": "system_operations",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Command mode mismatch: curl -I fetches headers only, curl -O downloads the full payload body.",
        "rationale": "Header inspection vs file artifact retrieval.",
    },
    {
        "id": "SYNTH-035",
        "query_a": "How do I search for a text pattern in files using grep on Linux?",
        "query_b": "How do I search for a text pattern in files using Select-String in PowerShell?",
        "domain": "system_operations",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_ENVIRONMENT_MISMATCH",
        "rejection_reason": "Platform dialect mismatch: GNU grep flags do not function in Windows PowerShell Select-String cmdlet.",
        "rationale": "POSIX bash utility vs Windows PowerShell ecosystem.",
    },
    {
        "id": "SYNTH-036",
        "query_a": "How do I view open network sockets and listening ports using ss on Linux?",
        "query_b": "How do I view active TCP connections on Windows using netstat in cmd?",
        "domain": "system_operations",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_ENVIRONMENT_MISMATCH",
        "rejection_reason": "Operating system mismatch: Linux iproute2 ss utility vs Windows netstat syntax.",
        "rationale": "Cross-platform network diagnostic command mismatch.",
    },

    # -----------------------------------------------------------------------
    # HISTORY & GEOGRAPHY (16 pairs: 8 safe, 8 unsafe)
    # -----------------------------------------------------------------------
    {
        "id": "SYNTH-037",
        "query_a": "What is the official capital of New Zealand?",
        "query_b": "Which city serves as the national capital of New Zealand?",
        "domain": "history_geography",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both queries ask for the national capital of New Zealand (Wellington).",
    },
    {
        "id": "SYNTH-038",
        "query_a": "What is the longest river in the world?",
        "query_b": "Which river is considered the longest on Earth?",
        "domain": "history_geography",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both ask for the longest river on Earth (the Nile / Amazon debate).",
    },
    {
        "id": "SYNTH-039",
        "query_a": "What year did the United States declare independence from Great Britain?",
        "query_b": "In what year was the American Declaration of Independence adopted?",
        "domain": "history_geography",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both ask for the historical year 1776.",
    },
    {
        "id": "SYNTH-040",
        "query_a": "What is the highest mountain peak above sea level on Earth?",
        "query_b": "Which mountain is the tallest peak in the world by elevation?",
        "domain": "history_geography",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both ask for Mount Everest's peak elevation.",
    },
    {
        "id": "SYNTH-041",
        "query_a": "What is the capital city of Japan?",
        "query_b": "Which city is the current capital of Japan?",
        "domain": "history_geography",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both ask for Tokyo.",
    },
    {
        "id": "SYNTH-042",
        "query_a": "What year did World War II officially end?",
        "query_b": "In which year did the Second World War conclude?",
        "domain": "history_geography",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both ask for the year 1945.",
    },
    {
        "id": "SYNTH-043",
        "query_a": "Which ocean is the largest on Earth by surface area?",
        "query_b": "What is the world's biggest ocean by size?",
        "domain": "history_geography",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both ask for the Pacific Ocean.",
    },
    {
        "id": "SYNTH-044",
        "query_a": "What is the capital city of Italy?",
        "query_b": "Which city is the national capital of Italy?",
        "domain": "history_geography",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both ask for Rome.",
    },
    {
        "id": "SYNTH-045",
        "query_a": "What is the constitutional capital of the Netherlands?",
        "query_b": "What city is the official seat of government of the Netherlands?",
        "domain": "history_geography",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Entity mismatch: Amsterdam is the constitutional capital, whereas The Hague is the seat of government and parliament.",
        "rationale": "Constitutional capital vs administrative seat of government.",
    },
    {
        "id": "SYNTH-046",
        "query_a": "What year did World War I begin?",
        "query_b": "What year did World War I end?",
        "domain": "history_geography",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Temporal mismatch: 1914 commencement vs 1918 armistice conclusion.",
        "rationale": "Opposite temporal endpoints of the same historical conflict.",
    },
    {
        "id": "SYNTH-047",
        "query_a": "Who was the first President of the United States under the Constitution?",
        "query_b": "Who was the first Vice President of the United States?",
        "domain": "history_geography",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Office mismatch: George Washington (President) vs John Adams (Vice President).",
        "rationale": "Different constitutional executive offices.",
    },
    {
        "id": "SYNTH-048",
        "query_a": "What is the capital of Brazil?",
        "query_b": "What was the historical capital of Brazil before Brasilia?",
        "domain": "history_geography",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_CONTEXT_MISMATCH",
        "rejection_reason": "Temporal context shift: modern planned capital (Brasilia) vs former historical capital (Rio de Janeiro / Salvador).",
        "rationale": "Present vs historical political capitals.",
    },
    {
        "id": "SYNTH-049",
        "query_a": "Which country has the largest land area in South America?",
        "query_b": "Which country has the longest north-to-south span in South America?",
        "domain": "history_geography",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Geographic metric mismatch: total territorial area (Brazil) vs linear latitudinal span (Chile).",
        "rationale": "Area measurement vs linear length.",
    },
    {
        "id": "SYNTH-050",
        "query_a": "What was the capital of the Byzantine Empire?",
        "query_b": "What was the capital of the Western Roman Empire during its collapse?",
        "domain": "history_geography",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Entity mismatch: Eastern Roman capital (Constantinople) vs Western Roman capital (Ravenna / Rome).",
        "rationale": "Divided imperial administrations.",
    },
    {
        "id": "SYNTH-051",
        "query_a": "What is the highest mountain in North America?",
        "query_b": "What is the highest mountain peak in South America?",
        "domain": "history_geography",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Continental scope mismatch: Denali (Alaska, North America) vs Aconcagua (Argentina, South America).",
        "rationale": "Different continents.",
    },
    {
        "id": "SYNTH-052",
        "query_a": "In what year did the Apollo 11 moon landing take place?",
        "query_b": "In what year did the Apollo 13 mission launch?",
        "domain": "history_geography",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Mission event mismatch: Apollo 11 lunar landing (1969) vs Apollo 13 aborted mission (1970).",
        "rationale": "Specific NASA mission numerical designations.",
    },

    # -----------------------------------------------------------------------
    # FINANCE & ECONOMICS (18 pairs: 10 safe, 8 unsafe)
    # -----------------------------------------------------------------------
    {
        "id": "SYNTH-053",
        "query_a": "What is the definition of gross domestic product (GDP) in macroeconomics?",
        "query_b": "Explain what GDP measures in an economy",
        "domain": "finance_economics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both ask for the definition of Gross Domestic Product.",
    },
    {
        "id": "SYNTH-054",
        "query_a": "How is the compound annual growth rate (CAGR) calculated?",
        "query_b": "Formula for calculating CAGR over an investment period",
        "domain": "finance_economics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both request the geometric annualized growth formula (End/Start)^(1/n) - 1.",
    },
    {
        "id": "SYNTH-055",
        "query_a": "What is the difference between nominal GDP and real GDP?",
        "query_b": "How does real gross domestic product differ from nominal GDP regarding inflation?",
        "domain": "finance_economics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both ask for the inflation adjustment contrast between nominal and real GDP.",
    },
    {
        "id": "SYNTH-056",
        "query_a": "What does liquidity refer to in corporate finance?",
        "query_b": "Definition of asset liquidity in financial markets",
        "domain": "finance_economics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both seek the financial definition of liquidity (ease of converting assets to cash).",
    },
    {
        "id": "SYNTH-057",
        "query_a": "What is the debt-to-equity ratio formula for evaluating leverage?",
        "query_b": "How do you calculate a company's debt-to-equity ratio?",
        "domain": "finance_economics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both ask for Total Debt divided by Total Shareholders' Equity.",
    },
    {
        "id": "SYNTH-058",
        "query_a": "What is the primary mandate of the Federal Reserve regarding monetary policy?",
        "query_b": "What are the two components of the US Federal Reserve's dual mandate?",
        "domain": "finance_economics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both ask for the Fed's dual mandate (maximum employment and price stability).",
    },
    {
        "id": "SYNTH-059",
        "query_a": "What is the definition of opportunity cost in microeconomics?",
        "query_b": "Explain the economic concept of opportunity cost",
        "domain": "finance_economics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both ask for the microeconomic definition of the next best alternative forgone.",
    },
    {
        "id": "SYNTH-060",
        "query_a": "How does inflation erode the purchasing power of money over time?",
        "query_b": "Explain why inflation decreases the purchasing power of a currency",
        "domain": "finance_economics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both ask for the economic mechanism linking price level inflation to real purchasing power.",
    },
    {
        "id": "SYNTH-061",
        "query_a": "What is the formula for calculating Return on Equity (ROE)?",
        "query_b": "How is Return on Equity computed from net income and shareholder equity?",
        "domain": "finance_economics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both ask for Net Income divided by Average Shareholders' Equity.",
    },
    {
        "id": "SYNTH-062",
        "query_a": "What is the price-to-earnings (P/E) ratio formula for a public stock?",
        "query_b": "How do you compute a stock's P/E ratio from price and EPS?",
        "domain": "finance_economics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both ask for Market Price per Share divided by Earnings Per Share (EPS).",
    },
    {
        "id": "SYNTH-063",
        "query_a": "What is the current spot exchange rate of EUR to USD today?",
        "query_b": "What was the historical exchange rate of EUR to USD in January 2020?",
        "domain": "finance_economics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_CONTEXT_MISMATCH",
        "rejection_reason": "Dynamic temporal obsolescence: real-time live currency quote vs fixed historical archive from 2020.",
        "rationale": "Serving a historical currency quote for a live exchange rate query is a severe cache hazard.",
    },
    {
        "id": "SYNTH-064",
        "query_a": "How do you calculate simple interest on a principal amount?",
        "query_b": "How do you calculate compound interest compounded monthly?",
        "domain": "finance_economics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Compounding mechanism mismatch: linear P*r*t formula vs exponential compounding P*(1 + r/12)^(12t).",
        "rationale": "Simple vs compound interest produce divergent financial values.",
    },
    {
        "id": "SYNTH-065",
        "query_a": "What is the difference between fiscal policy and monetary policy?",
        "query_b": "How does fiscal stimulus impact government sovereign debt levels?",
        "domain": "finance_economics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Topic scope mismatch: broad comparison between central bank tools and treasury taxation vs specific debt deficit dynamics.",
        "rationale": "Comparative definition vs sovereign debt fiscal impact.",
    },
    {
        "id": "SYNTH-066",
        "query_a": "What is the formula for Current Ratio in liquidity analysis?",
        "query_b": "What is the formula for Quick Ratio (Acid-Test Ratio)?",
        "domain": "finance_economics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_CONTEXT_MISMATCH",
        "rejection_reason": "Asset inclusion conflict: Current Ratio includes illiquid inventory, Quick Ratio strictly excludes inventory from current assets.",
        "rationale": "Different liquidity formulas with distinct numerator definitions.",
    },
    {
        "id": "SYNTH-067",
        "query_a": "How do call options work for an equity investor?",
        "query_b": "How do put options work for an equity investor?",
        "domain": "finance_economics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Contractual direction inversion: right to buy an underlying asset (bullish) vs right to sell (bearish).",
        "rationale": "Opposite derivative contracts and payoffs.",
    },
    {
        "id": "SYNTH-068",
        "query_a": "What is the current yield on the 10-year US Treasury note?",
        "query_b": "What is the current federal funds effective rate set by the FOMC?",
        "domain": "finance_economics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Financial benchmark mismatch: long-term bond market yield vs central bank overnight lending target rate.",
        "rationale": "Different interest rate benchmarks.",
    },
    {
        "id": "SYNTH-069",
        "query_a": "What is the definition of an expansionary monetary policy?",
        "query_b": "What is the definition of a contractionary monetary policy?",
        "domain": "finance_economics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Policy polarity inversion: lowering interest rates / increasing money supply vs raising interest rates / shrinking balance sheet.",
        "rationale": "Opposite macroeconomic central bank actions.",
    },
    {
        "id": "SYNTH-070",
        "query_a": "What is the difference between a stock dividend and a stock split?",
        "query_b": "What are the tax implications of qualified cash dividends in the US?",
        "domain": "finance_economics",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Corporate finance mechanics vs personal IRS tax liability on cash distributions.",
        "rationale": "Corporate share dilution mechanics vs tax code rules.",
    },

    # -----------------------------------------------------------------------
    # COMPUTER SCIENCE (Reinforcement: 16 pairs: 8 safe, 8 unsafe)
    # -----------------------------------------------------------------------
    {
        "id": "SYNTH-071",
        "query_a": "How do I merge two dictionaries in Python 3.9 or higher?",
        "query_b": "Python syntax for merging two dicts using the union operator",
        "domain": "computer_science",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both seek dict merge syntax in modern Python (the pipe operator dict_a | dict_b).",
    },
    {
        "id": "SYNTH-072",
        "query_a": "How does a stack differ from a queue in data structures?",
        "query_b": "Explain LIFO vs FIFO behavior in stack and queue structures",
        "domain": "computer_science",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Stack vs queue comparison is fundamentally defined by Last-In-First-Out vs First-In-First-Out.",
    },
    {
        "id": "SYNTH-073",
        "query_a": "How do you find the length of an array in JavaScript?",
        "query_b": "Property to get the number of elements in a JS array",
        "domain": "computer_science",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both ask for the .length property of a JavaScript Array.",
    },
    {
        "id": "SYNTH-074",
        "query_a": "What is the time complexity of binary search on a sorted list?",
        "query_b": "What is the Big-O worst-case runtime of binary search?",
        "domain": "computer_science",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both ask for the logarithmic time complexity O(log n) of binary search.",
    },
    {
        "id": "SYNTH-075",
        "query_a": "How do I flatten a 2D list into a 1D list in Python using list comprehension?",
        "query_b": "Flatten a nested list of lists with Python comprehension",
        "domain": "computer_science",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both request [item for sublist in matrix for item in sublist].",
    },
    {
        "id": "SYNTH-076",
        "query_a": "What is the difference between synchronous and asynchronous code execution?",
        "query_b": "Explain blocking synchronous vs non-blocking asynchronous programming",
        "domain": "computer_science",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Sync vs async execution is synonymous with blocking vs non-blocking I/O model.",
    },
    {
        "id": "SYNTH-077",
        "query_a": "How do I convert a string to lowercase in Python?",
        "query_b": "Python method to change all characters in a string to lower case",
        "domain": "computer_science",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both ask for the string .lower() method in Python.",
    },
    {
        "id": "SYNTH-078",
        "query_a": "What is polymorphism in object-oriented programming?",
        "query_b": "Explain the OOP concept of polymorphism with examples",
        "domain": "computer_science",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both request an explanation of polymorphism in object-oriented programming.",
    },
    {
        "id": "SYNTH-079",
        "query_a": "How do I sort an array in ascending order in JavaScript?",
        "query_b": "How do I sort an array in descending order in JavaScript?",
        "domain": "computer_science",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_CONTEXT_MISMATCH",
        "rejection_reason": "Polarity inversion: ascending comparator (a - b) violates descending sort requirement (b - a).",
        "rationale": "Opposite sorting order comparator.",
    },
    {
        "id": "SYNTH-080",
        "query_a": "How do I parse a JSON string into a Python dictionary?",
        "query_b": "How do I serialize a Python dictionary into a JSON string?",
        "domain": "computer_science",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Serialization direction inversion: deserialization (json.loads) vs serialization (json.dumps).",
        "rationale": "Opposite transformations between JSON string and Python data structure.",
    },
    {
        "id": "SYNTH-081",
        "query_a": "How do I encode a UTF-8 string into bytes in Python?",
        "query_b": "How do I decode bytes into a UTF-8 string in Python?",
        "domain": "computer_science",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Encoding direction mismatch: str.encode() yields bytes, bytes.decode() yields str.",
        "rationale": "Opposite string/bytes encoding transformations.",
    },
    {
        "id": "SYNTH-082",
        "query_a": "How do I push a new item onto the end of a JavaScript array?",
        "query_b": "How do I prepend a new item to the beginning of a JavaScript array?",
        "domain": "computer_science",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Array index position mismatch: append to end (Array.push) vs prepend to head (Array.unshift).",
        "rationale": "Tail insertion vs head insertion.",
    },
    {
        "id": "SYNTH-083",
        "query_a": "How do I write a breadth-first search (BFS) on a graph in Python?",
        "query_b": "How do I write a depth-first search (DFS) on a graph in Python?",
        "domain": "computer_science",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Graph traversal algorithm mismatch: queue-based FIFO level-order traversal vs stack/recursive depth exploration.",
        "rationale": "BFS vs DFS exhibit fundamentally different exploration orders.",
    },
    {
        "id": "SYNTH-084",
        "query_a": "How do I implement a shallow copy of a list in Python?",
        "query_b": "How do I implement a recursive deep copy of nested objects in Python?",
        "domain": "computer_science",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_CONTEXT_MISMATCH",
        "rejection_reason": "Object reference depth conflict: list.copy() copies references only, copy.deepcopy() clones arbitrary nested structures.",
        "rationale": "Shallow vs deep copying semantics.",
    },
    {
        "id": "SYNTH-085",
        "query_a": "How do I encrypt a string using AES in Python?",
        "query_b": "How do I decrypt an AES ciphertext string in Python?",
        "domain": "computer_science",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Cryptographic direction mismatch: plaintext encryption vs ciphertext decryption.",
        "rationale": "Inverse cryptographic transformations.",
    },
    {
        "id": "SYNTH-086",
        "query_a": "How do I install a Python package from PyPI using pip?",
        "query_b": "How do I completely uninstall a Python package using pip?",
        "domain": "computer_science",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Lifecycle polarity mismatch: package provisioning (pip install) vs package removal (pip uninstall).",
        "rationale": "Installation vs uninstallation.",
    },

    # -----------------------------------------------------------------------
    # SCIENCE & MEDICINE (Reinforcement: 16 pairs: 8 safe, 8 unsafe)
    # -----------------------------------------------------------------------
    {
        "id": "SYNTH-087",
        "query_a": "What is the powerhouse of the eukaryotic cell?",
        "query_b": "Which organelle is referred to as the cellular powerhouse?",
        "domain": "science_medicine",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both ask for the mitochondrion.",
    },
    {
        "id": "SYNTH-088",
        "query_a": "What is the chemical formula for common table salt?",
        "query_b": "What is the molecular formula of sodium chloride in chemistry?",
        "domain": "science_medicine",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both ask for NaCl.",
    },
    {
        "id": "SYNTH-089",
        "query_a": "What is Newton's first law of motion called?",
        "query_b": "Explain Newton's first law of motion regarding inertia",
        "domain": "science_medicine",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both explain the law of inertia.",
    },
    {
        "id": "SYNTH-090",
        "query_a": "What is the normal human body temperature in Celsius?",
        "query_b": "What is the average healthy body temperature in degrees Celsius?",
        "domain": "science_medicine",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both ask for 37 degrees Celsius (or 36.5-37.5 range).",
    },
    {
        "id": "SYNTH-091",
        "query_a": "What is the chemical symbol for gold on the periodic table?",
        "query_b": "Symbol for the element gold in chemistry",
        "domain": "science_medicine",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both ask for the chemical symbol Au.",
    },
    {
        "id": "SYNTH-092",
        "query_a": "What are the primary products of plant photosynthesis?",
        "query_b": "What molecules are produced during oxygenic photosynthesis in plants?",
        "domain": "science_medicine",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both seek glucose (C6H12O6) and oxygen (O2).",
    },
    {
        "id": "SYNTH-093",
        "query_a": "What is the speed of sound in dry air at room temperature?",
        "query_b": "How fast does sound travel through air at 20 degrees Celsius?",
        "domain": "science_medicine",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both ask for ~343 meters per second.",
    },
    {
        "id": "SYNTH-094",
        "query_a": "What type of blood cells are responsible for carrying oxygen throughout the body?",
        "query_b": "Which blood cells transport oxygen via hemoglobin?",
        "domain": "science_medicine",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Both ask for erythrocytes / red blood cells.",
    },
    {
        "id": "SYNTH-095",
        "query_a": "What is the difference between mitosis and meiosis in cell division?",
        "query_b": "What are the specific stages of meiosis I in gamete formation?",
        "domain": "science_medicine",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Scope mismatch: broad comparison between somatic cloning and reductive division vs specific meiosis I sub-stages.",
        "rationale": "Broad division comparison vs specific meiosis I stages.",
    },
    {
        "id": "SYNTH-096",
        "query_a": "What is the chemical symbol for sodium?",
        "query_b": "What is the chemical symbol for potassium?",
        "domain": "science_medicine",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Elemental entity mismatch: Sodium (Na) vs Potassium (K).",
        "rationale": "Different alkali metal elements.",
    },
    {
        "id": "SYNTH-097",
        "query_a": "What is the normal systolic blood pressure range in healthy adults?",
        "query_b": "What is the normal diastolic blood pressure range in healthy adults?",
        "domain": "science_medicine",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Physiological phase mismatch: ventricular contraction peak pressure (<120 mmHg) vs resting arterial pressure (<80 mmHg).",
        "rationale": "Systolic vs diastolic metrics.",
    },
    {
        "id": "SYNTH-098",
        "query_a": "How does type 1 diabetes differ from type 2 diabetes?",
        "query_b": "What are the first-line oral medications prescribed for type 2 diabetes?",
        "domain": "science_medicine",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Etiology comparison vs pharmacological treatment regimen (metformin).",
        "rationale": "Pathophysiological comparison vs drug prescription.",
    },
    {
        "id": "SYNTH-099",
        "query_a": "What is the atomic number of carbon?",
        "query_b": "What is the atomic mass of carbon-12?",
        "domain": "science_medicine",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Physics quantity mismatch: proton count (6) vs atomic mass (12.000 Da).",
        "rationale": "Atomic number vs atomic mass.",
    },
    {
        "id": "SYNTH-100",
        "query_a": "What is an endothermic chemical reaction?",
        "query_b": "What is an exothermic chemical reaction?",
        "domain": "science_medicine",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Thermodynamic enthalpy inversion: absorbs heat (+Delta H) vs releases heat (-Delta H).",
        "rationale": "Opposite thermodynamic heat flow definitions.",
    },
    {
        "id": "SYNTH-101",
        "query_a": "What causes seasonal influenza in humans?",
        "query_b": "What causes the common cold infection in humans?",
        "domain": "science_medicine",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Pathogen mismatch: Orthomyxoviridae (Influenza A/B) vs Rhinovirus/Coronavirus/Adenovirus.",
        "rationale": "Different respiratory viral etiologies.",
    },
    {
        "id": "SYNTH-102",
        "query_a": "What is the function of red blood cells in human circulation?",
        "query_b": "What is the function of white blood cells in human immunity?",
        "domain": "science_medicine",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Cellular physiological function mismatch: oxygen transport via hemoglobin vs immune defense and pathogen phagocytosis.",
        "rationale": "Erythrocytes vs leukocytes.",
    },

    # -----------------------------------------------------------------------
    # REALTIME NEWS & WEATHER (6 pairs: 1 safe, 5 unsafe)
    # -----------------------------------------------------------------------
    {
        "id": "SYNTH-103",
        "query_a": "What was the highest temperature ever recorded in Death Valley, California?",
        "query_b": "What is the record high temperature documented in Death Valley?",
        "domain": "realtime_news_weather",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": True,
        "taxonomy_class": "SAFE_EQUIVALENT",
        "rejection_reason": None,
        "rationale": "Historical meteorological record (56.7 C in 1913); static fact unaffected by live weather.",
    },
    {
        "id": "SYNTH-104",
        "query_a": "What is the current temperature in Central Park New York right now?",
        "query_b": "What was the average temperature in Central Park during July 2020?",
        "domain": "realtime_news_weather",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_CONTEXT_MISMATCH",
        "rejection_reason": "Temporal mismatch: live real-time weather observation vs archived monthly climate average.",
        "rationale": "Current live temperature vs historical climate summary.",
    },
    {
        "id": "SYNTH-105",
        "query_a": "What is the five-day weather forecast for London UK?",
        "query_b": "What is the typical climate and weather in London during October?",
        "domain": "realtime_news_weather",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_CONTEXT_MISMATCH",
        "rejection_reason": "Obsolescence mismatch: volatile 5-day predictive forecast vs multi-year historical climate averages.",
        "rationale": "Short-term weather forecast vs seasonal climate.",
    },
    {
        "id": "SYNTH-106",
        "query_a": "What are the latest breaking world news headlines today?",
        "query_b": "What were the major world news headlines on January 1, 2000?",
        "domain": "realtime_news_weather",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_CONTEXT_MISMATCH",
        "rejection_reason": "Temporal obsolescence: live dynamic newsfeed vs historical millennium archive.",
        "rationale": "Breaking news requires real-time retrieval; cached headlines from earlier dates create severe factual distortion.",
    },
    {
        "id": "SYNTH-107",
        "query_a": "Is there an active severe thunderstorm warning for Chicago right now?",
        "query_b": "What criteria does the National Weather Service use to issue severe thunderstorm warnings?",
        "domain": "realtime_news_weather",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Intent mismatch: real-time emergency alert query vs educational definition of NWS alert criteria.",
        "rationale": "Life-safety real-time alert check vs educational policy definition.",
    },
    {
        "id": "SYNTH-108",
        "query_a": "What is the current flight delay status at JFK airport today?",
        "query_b": "How many runways does JFK airport have in New York?",
        "domain": "realtime_news_weather",
        "semantic_similarity_level": "HIGH",
        "is_reuse_safe": False,
        "taxonomy_class": "UNSAFE_DIFFERENT_INTENT",
        "rejection_reason": "Dynamic operational query (FAA ground delay status) vs static infrastructure facility trivia.",
        "rationale": "Live operational flight status vs static infrastructure information.",
    },
]


def load_all_existing_queries() -> Dict[str, Set[str]]:
    """Load query strings from all 5 benchmark files."""
    datasets: Dict[str, Set[str]] = {}
    for name, path in EXISTING_DATASET_PATHS.items():
        if not path.exists():
            raise FileNotFoundError(f"Missing existing dataset: {path}")
        with open(path, "r", encoding="utf-8") as f:
            raw = json.load(f)
        queries = set()
        if isinstance(raw, list):
            for item in raw:
                if "query" in item:
                    queries.add(item["query"].strip().lower())
                if "query_a" in item:
                    queries.add(item["query_a"].strip().lower())
                if "query_b" in item:
                    queries.add(item["query_b"].strip().lower())
        elif isinstance(raw, dict):
            for item in raw.get("queries", []):
                if "query" in item:
                    queries.add(item["query"].strip().lower())
        datasets[name] = queries
    return datasets


def validate_synthetic_pairs(pairs: List[Dict[str, Any]], existing: Dict[str, Set[str]]) -> None:
    """Run strict 5-way leakage and uniqueness validation."""
    print("=" * 80)
    print("RUNNING STRICT LEAKAGE AND SCHEMA VALIDATION ON SYNTHETIC PAIRS")
    print("=" * 80)

    seen_ids: Set[str] = set()
    authored_queries: Set[str] = set()

    for idx, pair in enumerate(pairs, start=1):
        pid = pair["id"]
        if pid in seen_ids:
            raise ValueError(f"Duplicate ID found: {pid}")
        seen_ids.add(pid)

        qa = pair["query_a"].strip().lower()
        qb = pair["query_b"].strip().lower()

        # Check self-identity
        if qa == qb:
            raise ValueError(f"Pair {pid} has identical query_a and query_b: {qa}")

        # Check internal duplicate within synthetic set
        if qa in authored_queries:
            raise ValueError(f"Query A in pair {pid} is duplicate within synthetic set: {qa}")
        if qb in authored_queries:
            raise ValueError(f"Query B in pair {pid} is duplicate within synthetic set: {qb}")
        authored_queries.add(qa)
        authored_queries.add(qb)

        # Check leakage against all 5 existing datasets
        for ds_name, query_set in existing.items():
            if qa in query_set:
                raise ValueError(f"LEAKAGE in {pid} query_a against {ds_name}: {qa}")
            if qb in query_set:
                raise ValueError(f"LEAKAGE in {pid} query_b against {ds_name}: {qb}")

    print(f"[PASS] Total synthetic pairs validated: {len(pairs)}")
    print(f"[PASS] Total unique query strings generated: {len(authored_queries)}")
    print("[PASS] Zero leakage confirmed against all 5 existing datasets:")
    for ds_name, query_set in existing.items():
        print(f"       - {ds_name:<25}: {len(query_set):>4} queries checked (0 overlaps)")

    # Print domain breakdown
    from collections import Counter
    domain_counts = Counter(p["domain"] for p in pairs)
    domain_safe = Counter(p["domain"] for p in pairs if p["is_reuse_safe"])
    print("\nSynthetic Pair Breakdown by Domain:")
    for dom in sorted(domain_counts.keys()):
        total = domain_counts[dom]
        safe = domain_safe[dom]
        unsafe = total - safe
        print(f"  - {dom:<24}: Total={total:>2} (Safe={safe:>2}, Unsafe={unsafe:>2})")


def main() -> None:
    existing = load_all_existing_queries()
    validate_synthetic_pairs(SYNTHETIC_PAIRS, existing)

    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        json.dump(SYNTHETIC_PAIRS, f, indent=2)
    print(f"\nSuccessfully wrote {len(SYNTHETIC_PAIRS)} validated synthetic pairs to:\n  {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
